version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: src/rankedle/Dockerfile
    volumes:
      - .:/app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: src/web/Dockerfile
    volumes:
      - ./src/web:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
