# Generated by Django 5.1.5 on 2025-01-25 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Difficulty',
                'verbose_name_plural': 'Difficulties',
                'db_table': 'Difficulty',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.SmallIntegerField(verbose_name='Duration(s)')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('subname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subname')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Author')),
                ('mapper', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mapper')),
                ('upload_date', models.DateField(verbose_name='Upload date')),
                ('download_url', models.CharField(max_length=2048, verbose_name='Download URL')),
                ('cover_url', models.CharField(max_length=2048, verbose_name='Cover URL')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'db_table': 'Song',
            },
        ),
        migrations.CreateModel(
            name='MapDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Stars')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SongManager.difficulty', verbose_name='Difficulty')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulties', to='SongManager.map', verbose_name='Map ID')),
            ],
            options={
                'verbose_name': 'MapDifficulty',
                'verbose_name_plural': 'MapDifficulties',
                'db_table': 'MapDifficulty',
            },
        ),
    ]
