# Generated by Django 5.1.5 on 2025-01-25 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SongManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Map', 'verbose_name_plural': 'Maps'},
        ),
        migrations.AlterModelTable(
            name='map',
            table='Map',
        ),
    ]
