# Generated by Django 5.1.5 on 2025-01-26 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongManager', '0002_alter_map_options_alter_map_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdifficulty',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='difficulties', to='SongManager.map', verbose_name='Map ID'),
        ),
        migrations.AlterField(
            model_name='mapdifficulty',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Stars'),
        ),
    ]
