# Generated by Django 5.1.5 on 2025-01-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongManager', '0003_alter_mapdifficulty_map_alter_mapdifficulty_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdifficulty',
            name='difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SongManager.difficulty', verbose_name='Difficulty'),
        ),
    ]
