# Generated by Django 5.1.5 on 2025-01-26 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongManager', '0004_alter_mapdifficulty_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdifficulty',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SongManager.map', verbose_name='Map ID'),
        ),
    ]
