# Generated by Django 5.1.5 on 2025-01-26 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongManager', '0006_alter_mapdifficulty_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdifficulty',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SongManager.difficulty'),
        ),
        migrations.AlterField(
            model_name='mapdifficulty',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SongManager.map'),
        ),
    ]
