# Generated by Django 5.1.5 on 2025-01-26 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongManager', '0007_alter_mapdifficulty_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapdifficulty',
            options={},
        ),
        migrations.AlterField(
            model_name='mapdifficulty',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SongManager.difficulty', verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='mapdifficulty',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulties', to='SongManager.map', verbose_name='Map ID'),
        ),
        migrations.AlterModelTable(
            name='mapdifficulty',
            table=None,
        ),
        migrations.CreateModel(
            name='PermittedName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Permitted name')),
                ('map_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SongManager.map')),
            ],
            options={
                'verbose_name': 'PermittedName',
                'verbose_name_plural': 'PermittedNames',
                'db_table': 'PermittedName',
            },
        ),
    ]
