# Generated by Django 5.1.5 on 2025-01-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SongManager', '0008_alter_mapdifficulty_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapdifficulty',
            options={'verbose_name': 'MapDifficulty', 'verbose_name_plural': 'MapDifficulties'},
        ),
        migrations.AlterModelTable(
            name='mapdifficulty',
            table='MapDifficulty',
        ),
    ]
