# Generated by Django 5.1.5 on 2025-01-26 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongManager', '0009_alter_mapdifficulty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permittedname',
            name='map_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permitted_names', to='SongManager.map'),
        ),
    ]
