# Generated by Django 5.1.5 on 2025-01-26 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongManager', '0010_alter_permittedname_map_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdifficulty',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='difficulties', to='SongManager.map', verbose_name='Map ID'),
        ),
    ]
