# Generated by Django 5.1.5 on 2025-01-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongManager', '0012_alter_mapdifficulty_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdifficulty',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Stars'),
        ),
    ]
