# Generated by Django 5.1.5 on 2025-01-26 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SongManager', '0014_user_alter_mapdifficulty_stars_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
