# Generated by Django 5.1.5 on 2025-01-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongManager', '0015_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permittedname',
            old_name='map_fk',
            new_name='map',
        ),
        migrations.AlterField(
            model_name='permittedname',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
