# Generated by Django 5.1.5 on 2025-01-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongManager', '0016_rename_map_fk_permittedname_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdifficulty',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Stars'),
        ),
    ]
